### ISSUE TITLE
Parser returns an invalid Section object instead of None

### ISSUE THREAD

**Issue by LordSamanon** [VirginiaTech/pyvt#4]
Currently, due to a change server side, pyvt doesn't return None when an unavailable class section is queried, instead creating an invalid Section object which only consists of a 'CRN' that is actually an error message. #3

**Comment by forteddyt** [comment]
It may be because of summer break but I'll manually review and merge the PRs in place of @kevincianfarini if nothing happens by the end of this month.

**Comment by kevincianfarini** [comment]
Just saw these now. I'm on vacation at the moment so I will take a look to see what's going on when I have a chance. Should be within an day
